[env]
_.path = ["bin"]
HK_MISE = "1"

[tools]
hk = "latest"
pkl = "latest"
pinact = "latest"
shellcheck = "latest"
shfmt = "latest"
actionlint = "latest"
ripgrep = "latest"

[tasks.build]
run = "cargo build"

[tasks."build:release"]
run = "cargo build --release"

[tasks."build:release:install"]
description = "Build release binary and install to target directory"
depends = ["build:release"]
usage = 'flag "-t --target"'
run = """
target=${usage_target:-$HOME/.local/bin}
mkdir -p "$(dirname "$target")"
install -t "$target" ./target/release/trs
"""


[tasks.test]
run = "cargo test"

[tasks.lint]
run = "cargo clippy -- -D warnings"

[tasks.fmt]
run = "cargo fmt"

[tasks.check]
run = "cargo check"

[tasks.main]
run = "cargo run --"

[settings]
experimental = true
lockfile = true
